# Generated by Django 4.1.7 on 2024-06-12 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profi_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
    ]
