# Generated by Django 4.1.7 on 2024-06-15 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profi_main', '0004_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
