# Generated by Django 4.1.7 on 2024-06-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profi_main', '0005_delete_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdf',
            field=models.FileField(blank=True, upload_to='pdf/%Y/%m/%d'),
        ),
    ]
