# Generated by Django 4.1.7 on 2024-06-16 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profi_main', '0007_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ('email',), 'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратная связь'},
        ),
    ]
